from .config import (
    DETECTION_CONFIG,
    CAMERA_CONFIG,
    CAMERA_UPDATE_INTERVAL,
    AWAY_THRESHOLD,
    DATA_DIR,
    FACE_DB_PATH,
    ATTENDANCE_LOG
)

__all__ = [
    'DETECTION_CONFIG',
    'CAMERA_CONFIG',
    'CAMERA_UPDATE_INTERVAL',
    'AWAY_THRESHOLD',
    'DATA_DIR',
    'FACE_DB_PATH',
    'ATTENDANCE_LOG',
]